#Swagger docs:
#https://swagger.io/docs/specification/basic-structure/
openapi: 3.0.0
info:
  title: My Sample API.
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: /api
    description: API server
paths:
  /:
    get:
      summary: Returns a msg.
      description: 
      responses:
        '200':    # status code
          description: Some description
          content:
            application/json:
              schema:
                type: object
                properties:
                  type: msg


