apiVersion: v1
kind: Service
metadata:
  name: mearn
spec:
  selector:
    app: mearn
  ports:
  - port: 3000
    name: mearn
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mearn-lb
spec:
  selector:
    app: mearn
  ports:
    - name: mearn-lb
      port: 3000
      nodePort: 30100
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mearn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mearn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mearn
    spec:
      # subdomain: example
      containers:
        - name: mearn
          # image: busybox:1.31.1
          # command: [ "sleep", "3600" ]
          image: le999/mearn:1.0
          # imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: web
          env:
           - name: LOCAL
             value: "false"
